services:
  dev:
    build:
      context: ./docker
      dockerfile: Dockerfile.dev
      args:
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}

    image: ang-dev:ubuntu18.04
    container_name: ang-dev

    working_dir: /workspace

    volumes:
      - .:/workspace
      - ./.ccache:/home/developer/.ccache

    environment:
      CC: /usr/bin/gcc-8
      CXX: /usr/bin/g++-8
      CCACHE_DIR: /home/developer/.ccache

    command: sleep infinity
    stdin_open: true
    tty: true
